//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonAPayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BonAPayer()
        {
            this.Reglement = new HashSet<Reglement>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> MontantRetenu { get; set; }
        public Nullable<decimal> MontantTotalEcheance { get; set; }
        public Nullable<decimal> NetAPayer { get; set; }
        public string ValiderPar { get; set; }
        public Nullable<System.DateTime> DateValidation { get; set; }
        public Nullable<System.DateTime> DateSignature { get; set; }
        public Nullable<bool> EstRegle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reglement> Reglement { get; set; }
    }
}
