//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REG_FSS_DB : DbContext
    {
        public REG_FSS_DB()
            : base("name=REG_FSS_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annexe> Annexe { get; set; }
        public virtual DbSet<Banque> Banque { get; set; }
        public virtual DbSet<BonAPayer> BonAPayer { get; set; }
        public virtual DbSet<Caisse> Caisse { get; set; }
        public virtual DbSet<Devise> Devise { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<ModeReglement> ModeReglement { get; set; }
        public virtual DbSet<Reglement> Reglement { get; set; }
        public virtual DbSet<ReglementFacture> ReglementFacture { get; set; }
        public virtual DbSet<Retenu> Retenu { get; set; }
        public virtual DbSet<RoleFonctionnel> RoleFonctionnel { get; set; }
        public virtual DbSet<RoleTechnique> RoleTechnique { get; set; }
        public virtual DbSet<Rubrique> Rubrique { get; set; }
        public virtual DbSet<RubriqueRetenu> RubriqueRetenu { get; set; }
        public virtual DbSet<SuiviBancaire> SuiviBancaire { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<FoncTechRole> FoncTechRole { get; set; }
    }
}
