//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facture()
        {
            this.ReglementFacture = new HashSet<ReglementFacture>();
        }
    
        public int Id { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Echeance { get; set; }
        public Nullable<decimal> MontantTotale { get; set; }
        public Nullable<decimal> MontantDev { get; set; }
        public Nullable<decimal> MontantRegle { get; set; }
        public Nullable<decimal> MontantReste { get; set; }
        public string Statut { get; set; }
        public int IdFournisseur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReglementFacture> ReglementFacture { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
    }
}
