//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoncTechRole
    {
        public int IdTechRole { get; set; }
        public Nullable<int> IdFoncRole { get; set; }
        public int Id { get; set; }
    
        public virtual RoleFonctionnel RoleFonctionnel { get; set; }
        public virtual RoleTechnique RoleTechnique { get; set; }
    }
}
