//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fournisseur()
        {
            this.Facture = new HashSet<Facture>();
        }
    
        public int Id { get; set; }
        public string RaisonSocial { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<decimal> FraisGeneraux { get; set; }
        public Nullable<decimal> Solde { get; set; }
        public Nullable<bool> EstPhysique { get; set; }
        public Nullable<bool> EstMorale { get; set; }
        public Nullable<System.DateTime> EcheanceDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Facture { get; set; }
    }
}
