//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reglement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reglement()
        {
            this.ReglementFacture = new HashSet<ReglementFacture>();
            this.DetailReglement = new HashSet<DetailReglement>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Echeance { get; set; }
        public Nullable<System.DateTime> DateValidation { get; set; }
        public string ValiderPar { get; set; }
        public string DateReglement { get; set; }
        public Nullable<int> IdRetenu { get; set; }
        public Nullable<int> IdSuiviBancaire { get; set; }
        public Nullable<int> IdBonAPayer { get; set; }
    
        public virtual BonAPayer BonAPayer { get; set; }
        public virtual Retenu Retenu { get; set; }
        public virtual SuiviBancaire SuiviBancaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReglementFacture> ReglementFacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailReglement> DetailReglement { get; set; }
    }
}
