//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reglement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reglement()
        {
            this.ReglementFacture = new HashSet<ReglementFacture>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Echeance { get; set; }
        public Nullable<System.DateTime> DateValidation { get; set; }
        public string ValiderPar { get; set; }
        public string DateReglement { get; set; }
        public Nullable<int> IdDevise { get; set; }
        public Nullable<int> IdRetenu { get; set; }
        public Nullable<int> IdModeReglement { get; set; }
        public Nullable<int> IdBanque { get; set; }
        public Nullable<int> IdCaisse { get; set; }
        public Nullable<int> IdSuiviBancaire { get; set; }
        public Nullable<int> IdBonAPayer { get; set; }
    
        public virtual Banque Banque { get; set; }
        public virtual BonAPayer BonAPayer { get; set; }
        public virtual Caisse Caisse { get; set; }
        public virtual Devise Devise { get; set; }
        public virtual ModeReglement ModeReglement { get; set; }
        public virtual Retenu Retenu { get; set; }
        public virtual SuiviBancaire SuiviBancaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReglementFacture> ReglementFacture { get; set; }
    }
}
