//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReglementFacture
    {
        public int Id { get; set; }
        public int IdFacture { get; set; }
        public int IdReglement { get; set; }
        public Nullable<decimal> MontantTotale { get; set; }
    
        public virtual Facture Facture { get; set; }
        public virtual Reglement Reglement { get; set; }
    }
}
