//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubriqueRetenu
    {
        public int Id { get; set; }
        public int IdRubrique { get; set; }
        public int IdRetenu { get; set; }
        public Nullable<decimal> MontantHt { get; set; }
        public Nullable<double> Tva { get; set; }
        public Nullable<decimal> MontantTtc { get; set; }
        public Nullable<int> IdAnnexe { get; set; }
    
        public virtual Annexe Annexe { get; set; }
        public virtual Retenu Retenu { get; set; }
        public virtual Rubrique Rubrique { get; set; }
    }
}
