//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubriqueRetenu
    {
        public int Id { get; set; }
        public int IdRubrique { get; set; }
        public int IdRetenu { get; set; }
        public Nullable<decimal> MontantHt { get; set; }
        public Nullable<double> Tva { get; set; }
        public Nullable<decimal> MontantTtc { get; set; }
        public Nullable<int> IdAnnexe { get; set; }
    
        public virtual Annexe Annexe { get; set; }
        public virtual Retenu Retenu { get; set; }
        public virtual Rubrique Rubrique { get; set; }
    }
}
