//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int Id { get; set; }
        public Nullable<int> IdRoleFonctionnel { get; set; }
        public string NomUtilisateur { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string MotDePasse { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<bool> EstActive { get; set; }
    
        public virtual RoleFonctionnel RoleFonctionnel { get; set; }
    }
}
