//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENGAGEMENT.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int Id { get; set; }
        public Nullable<int> IdRoleFonctionnel { get; set; }
        public string NomUtilisateur { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string MotDePasse { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<bool> EstActive { get; set; }
    
        public virtual RoleFonctionnel RoleFonctionnel { get; set; }
    }
}
